### ISSUE TITLE
Hadoop LZO fails to build with Open JDK 1.6 & Ubuntu.

### ISSUE THREAD

**Issue by deepujain** [twitter/hadoop-lzo#65]
I could not find how to communicate with you. I ran ant clean test at hadoop-lzo directory and see following error.
     [exec] ompressor.c:273:3: warning: implicit declaration of function ‘strstr’ [-Wimplicit-function-declaration]
     [exec] /home/deepakkv/softwares/hadoop-lzo/src/native/impl/lzo/LzoCompressor.c:273:14: warning: incompatible implicit declaration of built-in function ‘strstr’ [enabled by default]
     [exec] make: *** [impl/lzo/LzoCompressor.lo] Error 1

To fix above i included string.h in /home/deepakkv/softwares/hadoop-lzo/src/native/impl/lzo/LzoCompressor.c and ran into below error
     [exec] /home/deepakkv/softwares/hadoop-lzo/src/native/impl/lzo/LzoCompressor.c: In function ‘Java_com_hadoop_compression_lzo_Lzodepbase=`echo impl/lzo/LzoCompressor.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
     [exec] 	/bin/bash ./libtool --tag=CC   --mode=compile gcCompressor_initIDs’:
     [exec] /home/deepakkv/softwares/hadoop-lzo/src/native/impl/lzo/LzoCompressor.c:125:37: error: expected expression before ‘,’ token
     [exec] make: *** [impl/lzo/LzoCompressor.lo] Error 1
 

Environment
LIBRARY_PATH=/usr/local/lzo-2.06/lib
JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64/
Linux ubuntu 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
C_INCLUDE_PATH=/usr/local/lzo-2.06/include

**Comment by sjlee** [comment]
This should not be an issue at this point. Closing an old issue.
